### ISSUE TITLE
Can not open Player Details! Breakdown

### ISSUE THREAD

**Issue by windymindy** [Bunny67/Details-WotLK#59]
Hello.
Sometimes one can not click on self in the Damage Done pane to open Player Details! Breakdown.

https://www.youtube.com/watch?v=1tRiHV90L80

Thank you for your work.

**Comment by sky1700** [comment]
I also have this issue sometimes !

**Comment by mattisamo** [comment]
Also have this issue

**Comment by windymindy** [comment]
The problem is that **player.spec** is not **nil** and equals **0**.
https://github.com/Bunny67/Details-WotLK/blob/81e2b2d4649f27673e7ae310d5e46edbc00effac/Details/gumps/janela_info.lua#L1496

The quick fix is to enumerate all the places in the code that access **class_specs_coords**

- https://github.com/Bunny67/Details-WotLK/blob/81e2b2d4649f27673e7ae310d5e46edbc00effac/Details/classes/classe_custom.lua#L717
- https://github.com/Bunny67/Details-WotLK/blob/19aeece695d9ae0fb7333f6aa11fafb6cc3c7984/Details/functions/playerclass.lua#L541
- https://github.com/Bunny67/Details-WotLK/blob/0f07e468990cb0b451ab783dac3de86fe19bb247/Details/gumps/janela_principal.lua#L2074
- and so on...

and guard them alike 
https://github.com/Bunny67/Details-WotLK/blob/81e2b2d4649f27673e7ae310d5e46edbc00effac/Details/classes/classe_damage.lua#L2805

`// janela_info.lua#L1496
		if (player.spec and player.spec > 0) then
			window.classe_icone:SetTexture ([[Interface\AddOns\Details\images\spec_icons_normal_alpha]])
			window.classe_icone:SetTexCoord (_unpack (_detalhes.class_specs_coords [player.spec]))
			--esta_barra.icone_classe:SetVertexColor (1, 1, 1)
		else
`

A configuration workaround is to disable Options -> Appearance -> Bars: General -> Icons: -> Icon File = No Icon.
This way **track_specs** will be **nil** and no spec icons will lead to error.
https://github.com/Bunny67/Details-WotLK/blob/0f07e468990cb0b451ab783dac3de86fe19bb247/Details/gumps/janela_principal.lua#L4185
https://github.com/Bunny67/Details-WotLK/blob/0f07e468990cb0b451ab783dac3de86fe19bb247/Details/gumps/janela_principal.lua#L4187

The target approach is to find out where and why does **spec** property gets assigned to **0**, maybe in **_detalhes:ReGuessSpec** or somewhere else.
https://github.com/Bunny67/Details-WotLK/blob/19aeece695d9ae0fb7333f6aa11fafb6cc3c7984/Details/functions/playerclass.lua#L233

**Comment by ajseward** [comment]
Spec guessing is based on what the player casts. In the video resetting all data I assume also resets the cached player data, and the spell being used is not tracked by details. 

https://github.com/Bunny67/Details-WotLK/blob/8ad26762d1ab6a85debcfc0960dbcc13ddbe13ab/Details/functions/spells.lua#L11

Since retail doesn't have spell ranking anymore a lot of the ranks below their lvl 80 versions are missing from this list, and since you're on ascension I assume it's using the TBC Appropriate ranks, which means they are probably not in the spell list, thus spec isn't guessed and it's set to 0. (it would work fine for spells with no rank, bloodlust for example).

Based on how bunny likes to backport addons, it's likely updating the spell list would be the appropriate fix rather than hiding the error.

**Comment by windymindy** [comment]
So true.
But why one would set it to 0, when you can leave it nil so other code does not break.
There is only one place that checks for 0 value explicitly and 3 or so more that do that implicitly.

**Comment by ajseward** [comment]
I'd assume since on retail details its an impossible state since every spell is accounted for or handled by other spec checking (which doesn't work on ascension specifically).
This issue is pretty unique to ascension, and can be solved by going through and updating the spell list with each rank for every spell.

**Comment by windymindy** [comment]
And this issue only happens only when one clicks on himself.
Maybe spec guessing is broken for player running the addon because it is expected to get spec from api.
And there should be an heuristic to consolidate ranks based on spell's common name.
Anyways when the code does not meet its own expectations I regard this as corrupting data inconsistency.

**Comment by windymindy** [comment]
Anyways, I solved my problem by that patch of the guarding condition and/or configuration.
Ty for the port again.
Feel free to close the issue.

**Comment by Szyler** [comment]
> 
> 
> Spec guessing is based on what the player casts. In the video resetting all data I assume also resets the cached player data, and the spell being used is not tracked by details.
> 
> https://github.com/Bunny67/Details-WotLK/blob/8ad26762d1ab6a85debcfc0960dbcc13ddbe13ab/Details/functions/spells.lua#L11
> 
> Since retail doesn't have spell ranking anymore, most of the spells were just replaced with their lvl 80 versions, so a lot of the ranks below their lvl 80 versions are missing from this list, and since you're on ascension I assume it's using the TBC Appropriate ranks, which means they are probably not in the spell list, thus spec isn't guessed and it's set to 0. (it would work fine for spells with no rank, bloodlust for example).
> 
> Based on how bunny likes to backport addons, it's likely updating the spell list would be the appropriate fix rather than hiding the error.

I fixed this issue on Ascension by just adding all ranks of abilities to the _detalhes.SpecSpellList table, so I can confirm that works as a fix.
